### ISSUE TITLE
set eln-cache depending on emacs version

### ISSUE THREAD

**Issue by mclearc** [SystemCrafters/rational-emacs#103]
Right now the setting of eln-cache is

```emacs-lisp
 ;; Set the right directory to store the native compilation cache
  (add-to-list 'native-comp-eln-load-path (expand-file-name "eln-cache/" user-emacs-directory)))
```
This is the default. But should the user decide to change the location it won't work properly on emacs 29. Instead  you need to use the new function `startup-redirect-eln-cache`. You can see the report from this [bug report](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=53891) and the related [stack exchange discussion](https://emacs.stackexchange.com/a/70478/11934). So I recommend putting something like the following instead:

```emacs-lisp
;; Put eln-cache dir in cache directory
;; NOTE the method for setting the eln-cache dir depends on the emacs version
(when (fboundp 'startup-redirect-eln-cache)
  (if (version< emacs-version "29")
      (add-to-list 'native-comp-eln-load-path (concat "path/to/etc/dir" "eln-cache/"))
    (startup-redirect-eln-cache (concat "path/to/etc/dir" "eln-cache/"))))
```

**Comment by jeffbowman** [comment]
Thanks for the info! We would welcome a PR for this issue.

**Comment by mclearc** [comment]
Happy to do that. One question though -- right now the eln-cache setting occurs before `rational-config-path` is set. Do you want me to move the eln settings to after that point in the file? Or is there a reliable hard-coded setting you'd prefer?

**Comment by jeffbowman** [comment]
> Happy to do that. One question though -- right now the eln-cache setting occurs before `rational-config-path` is set. Do you want me to move the eln settings to after that point in the file? Or is there a reliable hard-coded setting you'd prefer?

Probably should move it to after the `rational-config-path` is set.
