### ISSUE TITLE
Should `rational-completion.el` be named `rational-minibuffer-selection.el` instead?

### ISSUE THREAD

**Issue by jeffbowman** [SystemCrafters/rational-emacs#106]
Completion may be confusing in the general sense. Corfu/Company/et. al. seem to be associated with the concept of `completion`, while Vertico/Orderless/et. al. seem to be associated with the concept of minibuffer selection or filtering.  I think more people think of completion from the IDE perspective ala function/variable filtering, live templates, etc. 

Thoughts? Maybe it's good enough as it is?

**Comment by jeastman** [comment]
I am not so sure it is as evenly divided as completion vs. selection. I think I see what you are hinting at, but I believe all of these things are very closely connected.. and ultimately about completion. There is also a bit of terminology application that is different with emacs (along with the whole use of the term 'window' debate).

Corfu is a completion at point UI, so it is clearly only about completion. Orderless defines itself as a _completion style_, making it tightly bound to completion. While this is most often seen in the minibuffer, I don't believe it is limited to it. 
Vertico is a minibuffer completion framework. While it is 'tied' to the minibuffer, it is still about completion. 

When you say selection, I do not immediately think about 'selecting' something in the minibuffer, I think more along the lines of 'text selection' in a buffer.

So... I don't really think of them as separate things. I am open to other opinions though.

**Comment by jeffbowman** [comment]
No further responses, we'll leave it alone.
