### ISSUE TITLE
Enhance whitespace configuration (rational-editing.el) to be able to customize modes in which it is used

### ISSUE THREAD

**Issue by jeffbowman** [SystemCrafters/rational-emacs#107]
This can be done similar to how we handle displaying line numbers. Should look into buffer-local configuration for Makefiles as tab indentation is required for `make` to work, may need to review docs for CMake and see if the same applies for that mode as well and adjust the `whitespace-style` to use `indentation::tabs` instead for those modes.

**Comment by erikLundstedt** [comment]
> This can be done similar to how we handle displaying line numbers. Should look into buffer-local configuration for Makefiles as tab indentation is required for `make` to work, may need to review docs for CMake and see if the same applies for that mode as well and adjust the `whitespace-style` to use `indentation::tabs` instead for those modes.

as long as there´s an option for a tabs-only-person like me, i'm happy

**Comment by jeffbowman** [comment]
> as long as there´s an option for a tabs-only-person like me, i'm happy

That is achievable by (possibly) turning off `whitespace` mode in your config, or possibly customizing `whitespace-styles` to use `indentation::tab` instead of `indentation::space` and then you probably also want to set `indent-tabs-mode` to `t`.

```emacs-lisp
    ;; In your `config.el'
   
    ;; this *after* (require 'rational-defaults) if you use the module, perhaps even if you don't just to be explicit
    (customize-set-variable 'indent-tabs-mode t)

    ;; this *after* (require 'rational-editing), not needed if you don't use the rational-editing module
    ;;
    ;; assuming the continued use of whitespace-mode
    (customize-set-variable 'whitespace-style '(face tabs empty trailing tab-mark indentation::tab)

    ;; or not using it
    (remove-hook 'prog-mode-hook #'whitespace-mode)
    (remove-hook 'text-mode-hook #'whitespace-mode)
```

Hope that makes sense.
