### ISSUE TITLE
mention minimum version of emacs in readme

### ISSUE THREAD

**Issue by HumHongeKamyaab** [SystemCrafters/rational-emacs#109]
I tried the config with 26.3 in ubuntu 20.04 LTS but it had the following issues
- no early-init support
- issue with this line https://github.com/SystemCrafters/rational-emacs/blob/7c003ab17b33fbfd29601dbbd3b591e6e81ea3fb/modules/rational-completion.el#L48
- issue with this line https://github.com/SystemCrafters/rational-emacs/blob/7c003ab17b33fbfd29601dbbd3b591e6e81ea3fb/modules/rational-defaults.el#L51
There may be other issues, but it may be better to support rational-emacs for 27 and above.

**Comment by jeffbowman** [comment]
Great suggestion! Would you submit a PR for this change?
