### ISSUE TITLE
Make the theme customizable / optional

### ISSUE THREAD

**Issue by telenieko** [SystemCrafters/rational-emacs#133]
The current coding of `rational-ui` installs `doom-themes` always.

This should be optional as the user may want to use other themes.

Any pointers on how that could be achieved?

**Comment by jeffbowman** [comment]
One possible solution would be to add a variable, for example `rational-ui-use-doom-themes` which might default to `nil`. Then if the user chooses to set the value to `t` in their `config.el` file, the `:set` attribute on the `defcustom` form could install the package. 

You can see an example to follow in the `rational-ui-display-line-numbers` form. 

Feel free to give it a shot and send a PR! :-)

**Comment by telenieko** [comment]
> However, one more thing... just installing themes makes them available to use, it does not mandate their use. You'll see in the early-config.el file we actually load the built-in deeper-blue theme. 

I understand the `deeper-blue` theme is loaded so that if everything goes wrong your emacs window is less ugly, also "avoids the white screen flash on startup". But the difference is `deeper-blue` is builtin while `doom-themes` is not.

So, we are currently downloading a package that the user might not want/need at all. 
Also in a way that's kind of unexpected as the `load-theme` call is in the "Example" configuration one (a newbie like me) would guess that not calling `(load-theme 'doom-one t)` would not download the package at all. (wrong guess I know)

The point being that unless `rational-emacs` does intend to "prioritize" `doom-themes` given that the `load-theme` call is already in the Example, not inside `rational-ui.el` maybe it would just make sense to leave all the "theme related" code in the example?

The alternative would be to introduce a new variable (`rational-ui-use-doom-themes`) that would only translate into a call to `(rational-package-install-package 'doom-themes)`. If it defaults to `nil` add a mention on the example config before the call to `load-theme`. If it defaults to `t` document the behaviour somewhere.

IMO It feels like overkill to introduce the variable and document it for "just" wrapping a call to `*-install-package`.

**Comment by jeffbowman** [comment]
Thanks for your comments! 

There are several options to choose from, for sure. The one you suggest is absolutely valid.  Would you be willing to put together a PR with your ideas?
