### ISSUE TITLE
there are some bugs in package "helpful"

### ISSUE THREAD

**Issue by pipiTan** [SystemCrafters/rational-emacs#140]
C-h f will throw error helpful--autoloaded-p: wrong number of arguments.
C-h v : elisp-refs-read-all buffer-forms: unexpected error whilst reading /usr/share/emacs/........
but I perform describe-function, descirbe-variable(not "helpful" provide) via M-x, they work well.

**Comment by jeffbowman** [comment]
Thanks for the report, this likely has more to do with the helpful package, but can you please post the error message you are seeing? Emacs usually puts this in a stack trace, if you could please post that here for the errors you are seeing, it will be easier for us to help you.

**Comment by pipiTan** [comment]
> Thanks for the report, this likely has more to do with the helpful package, but can you please post the error message you are seeing? Emacs usually puts this in a stack trace, if you could please post that here for the errors you are seeing, it will be easier for us to help you.

Thanks for reply :)
The first is C-h f, the second is C-h v.
![function](https://user-images.githubusercontent.com/18749923/165483506-bff77303-d81e-4d2f-ba90-e838731b833a.jpg)
![variable](https://user-images.githubusercontent.com/18749923/165483535-4d59545d-4e14-4c7f-9dd7-37b09ddd1ee4.jpg)
![0](https://user-images.githubusercontent.com/18749923/165483883-3fe94e3b-20e9-4ebb-8b20-4fc0025d478a.jpg)

**Comment by jeffbowman** [comment]
Hmm... not much to go on. What version of Emacs are you using, and what version of Helpful do you have installed?

**Comment by pipiTan** [comment]
> Hmm... not much to go on. What version of Emacs are you using, and what version of Helpful do you have installed?

helpful version is 0.18
![截屏图片](https://user-images.githubusercontent.com/18749923/165674406-d27e4f31-c300-4fd1-908c-1e2b68b66603.jpg)

**Comment by pipiTan** [comment]
> Thanks! The answer is your version of Emacs has a breaking change in one of the dependencies used by helpful. There is a fix for the helpful package, see [this pull request](https://github.com/Wilfred/helpful/pull/283) However, this fix is not in helpful 0.18. This is not a surprise as Emacs 29.0.50 is the development version of Emacs. so I would not expect the `helpful` package maintainer to tag their package with a new version as a release in this case.
> 
> You can use the MELPA version of helpful by following steps from either of these processes:
> 
>     * The first way:
> 
> 
>     1. In your `early-config.el` file add `(add-to-list 'package-pinned-packages '(helpful . "melpa")`
> 
>     2. Stop Emacs (including shutting down the daemon if you use it).
> 
>     3. Delete the `helpful-0.18` folder from your installed packages (usually found in your `user-emacs-directory`/elpa folder).
> 
>     4. Start Emacs, helpful should be installed from MELPA
> 
> 
>     * The second way:
> 
> 
>     1. run `M-x list-packages` in Emacs
> 
>     2. find the installed `helpful` package and press the RET key to open information about it.
> 
>     3. Look for the text "Other versions", one of the other versions listed should be from MELPA.
> 
>     4. Tab until the point is on the MELPA version and press the RET key
> 
>     5. At the top there will be an `Install` button, you can click on this with your mouse or move the point there and press RET to install that version.
> 
>     6. You will now have both versions installed, if you wish to delete the 0.18 version, go back to the list of packages, find that version in the list, press the 'D' key to mark it for deletion and then the 'X' to delete that version.
> 
> 
> This should resolve your problem. You may need to restart Emacs.
> 
> Does this help you?

Oh my god!! It works. Appreciate you:)

**Comment by jeffbowman** [comment]
Glad that helped!! May we close this issue as resolved?

**Comment by pipiTan** [comment]
Sure :)

> Glad that helped!! May we close this issue as resolved?
