### ISSUE TITLE
If I remove rational-evil, will I get a Vanilla Emacs ?

### ISSUE THREAD

**Issue by wereket** [SystemCrafters/rational-emacs#142]
disabling rational-emacs, will it hinder the overall experience ? I want to disable evil-mode

**Comment by jeastman** [comment]
Not requiring 'rational-evil' should work just fine. I do not use the evil bindings either.

**Comment by jeffbowman** [comment]
I also don't use `evil` keybindings in my configuration. All of the modules in Rational Emacs are optional. Use whichever ones you need or none of them and write your own! Whatever works best for you!
