### ISSUE TITLE
rational-compile: only compile required modules

### ISSUE THREAD

**Issue by sthesing** [SystemCrafters/rational-emacs#144]
If a user requires the `rational-compile` module, it attempts to compile all modules, regardless whether the user uses them or not. That leads to compiler errors, because dependencies of unused modules probably aren't installed.

For example, even if a user doesn't require `rational-evil` in their `config.el`, `rational-compile` will attempt to compile `modules/rational-evil.el`. This will fail if `evil` isn't installed.

So it probably would be best to only compile the modules the user actually requires in their `config.el`.

(Tagging @abarocio80 the original author of `rational-compile`).

**Comment by abarocio80** [comment]
That's a real issue.

I guess it is not that difficult to fix with a list of applied modules, but that would add to the user the task to maintain such a list.

I think that one way to address that problem would be to create a function (or macro) to apply the module and to add that module to the list of modules to compile.

Which way could be better? Or are there another approaches to this issue? I ask to the community.

**Comment by jeffbowman** [comment]
Closing this after merging #145
