### ISSUE TITLE
saving config.org does not create config.el

### ISSUE THREAD

**Issue by wereket** [SystemCrafters/rational-emacs#146]
Hello
I copied example-configl.org to ~/.rational-emacs/config.org
I modified config.org and saving does not create config.el.
I did cp config.org config.el
changes to config.org are not showing in config.el once saved

**Comment by jeffbowman** [comment]
@sthesing Can you help here?

**Comment by sthesing** [comment]
Oops, that's a bootstrapping issue that I forgot to mention in `examples/README.org`, sorry. `config.org`has to be tangled manually for the first time, after that, the tangling hook does the rest.
I'll prepare a PR with an updated README.
@wereket :  Open `config.org` in Emacs, hit `M-x` and run `org-babel-tangle`. That will generate the your first `config.el`. Restart Emacs. After that, when you save changes in `config.org`, the tangling will run automatically.

**Comment by sthesing** [comment]
Hm... now that I'm rewording the instructions in `examples/example-config.org`, I'm wondering: 

**What would be the easiest (and least error-prone) way to do get a `config.org`-setup going?**

### Option 1:

- copy `examples/example-config.el` to `~/.rational-emacs/config.el`
- copy `examples/example-config.org` to `~/.rational-emacs/config.org`
- restart Emacs

### Option 2:
- copy `examples/example-config.org` to `~/.rational-emacs/config.org`
- hit "M-x" and run `org-babel-tangle`
- restart Emacs

### Option 3:
- copy `examples/example-config.org` to `~/.rational-emacs/config.org`
- create an empty `~/.rational-emacs/config.el`
- paste the first snippet of `config.org` to the empty `config.el`
- restart Emacs

Opinions? Ideas?

@wereket What would have been the least misunderstandable approach for you?

**Comment by wereket** [comment]
Thank you, in my opinion this line could be added to the Customization section 
"M-x and run org-babel-tangle config.org"

**Comment by jeffbowman** [comment]
@sthesing, I don't use literate configurations, but your `option 2` seems to be the least confusing of the three. The confusion starts with "why do I need to manually copy things (option 3), shouldn't this just work^tm?" or "Why copy the example config.el when it's just going to be overwritten when I modify the config.org (option 1)"?

But those might be questions coming from someone who doesn't use literate config files and may/may not understand how that works anyway. Just my 2 cents.
