### ISSUE TITLE
Better support for long lines

### ISSUE THREAD

**Issue by Gavinok** [SystemCrafters/rational-emacs#15]
The bidi settings since some people do need bidirectional support but that's pretty rare. Either way the `global-so-long-mode` is a must. Basically it turns off features that would have stopped Emacs in it's tracks whenever long lines are detected.

```lisp
  (setq-default bidi-paragraph-direction 'left-to-right)
  (when (version<= "27.1" emacs-version)
    (setq bidi-inhibit-bpa t)
    (global-so-long-mode 1))
```

**Comment by japhir** [comment]
Why do you set this only for versions older than 27.1? Is it the default now?
I had below in my config:
```elisp
  (setq-default bidi-paragraph-direction 'left-to-right)
  (setq-default bidi-inhibit-bpa t)
```

**Comment by Gavinok** [comment]
Good question I actually meant the other way around haha. It's default apparently changed to nil at some point according to the docs. Don't think it's the default now.

**Comment by Gavinok** [comment]
This would make more sense I now that you mention it.
```lisp
  (setq-default bidi-paragraph-direction 'left-to-right)
  (setq-default bidi-inhibit-bpa t)
  (global-so-long-mode 1)
```

**Comment by daviwil** [comment]
I'd definitely accept a PR for it!

**Comment by Gavinok** [comment]
Ugh I was being lazy but I guess I should haha.
