### ISSUE TITLE
module section in config.org, pressing enter does not work

### ISSUE THREAD

**Issue by wereket** [SystemCrafters/rational-emacs#152]
![image](https://user-images.githubusercontent.com/89839215/167760439-863de7eb-7f7b-4419-b8d5-535fe4c5b387.png)

**Comment by ajxn** [comment]
What are you trying to do, and what do you do?
What do you expect to happen?  What actually happen?

It is hard to understand the problem just from this image.

**Comment by wereket** [comment]
add another line pressing enter does not work to add more lines in that section

**Comment by wereket** [comment]
it worked now, it was strange to get on the next line after pressing enter now it seem to work, in config.org inside lisp code block it was strange to not get on the next line after pressing enter.
Now it works, I never had this issue before
