### ISSUE TITLE
Non printable characters introduced by 236af05c

### ISSUE THREAD

**Issue by telenieko** [SystemCrafters/rational-emacs#162]
Hi,

Commit 236af05c8d4ee23cb0493d386bf0aeb147f1cd0c introduced some non printable characters. They don't show in github diffs but you can see them in a terminal, or with `git blame`:
![image](https://user-images.githubusercontent.com/10505/173532209-ce36633b-8c4b-43ce-bfcf-feb46e2e8ef5.png)

This is `rational-completion.el`

What is the point of those characters? Being non printable it is quite easy they will be accidentally removed by anyone changing nearby code.

**Comment by jeffbowman** [comment]
Those are page markers, you can use them to navigate with `C-x [` and `C-x ]`.  Commonly used to help navigate through chunks/sections of code. See `C-h n` and `package.el` for other examples of usage.
