### ISSUE TITLE
Can we add `(delete-selection-mode t)` to rational?

### ISSUE THREAD

**Issue by mattmc3** [SystemCrafters/rational-emacs#178]
Many popular emacs distributions enable `(delete-selection-mode t)` which deletes a selection when typing over it. This is such a common behavior in other editors that it's jarring that emacs doesn't do it by default.

There's been a lot of [discussion](https://emacs.stackexchange.com/questions/32205/delete-selection-mode-not-a-default) in various places about the merits. It's easy to disable again if a user doesn't like it and there's no performance impact to changing this behavior. It seems widely accepted that this is a poor default choice in modern emacs and I would propose adding it to rational or at least discussing the merits here.

Here are links to where some other popular emacs distros enable this:
* [Doom](https://github.com/doomemacs/doomemacs/blob/9ec60d9ab9eb5d9b098e2452395156b622cce624/modules/config/default/%2Bemacs.el#L10)
* [Prelude](https://github.com/bbatsov/prelude/blob/33f97ff8523150572724d4d086b3b58e507c5173/core/prelude-editor.el#L50)
* [Purcell](https://github.com/purcell/emacs.d/blob/b484cada4356803d0ecb063d33546835f996fefe/lisp/init-editing-utils.el#L36)
* [Centaur](https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-edit.el#L38)

**Comment by jeffbowman** [comment]
Done.
