### ISSUE TITLE
config.el not loading

### ISSUE THREAD

**Issue by md-arif-shaikh** [SystemCrafters/rational-emacs#185]
Hi, I just wanted to give this a shot. This is what I did,
- cloned to `~/.emacs.d`
- moved `example-config.org` and `example-config.el` to `~/.emacs.d` as `config.org` and `config.el`, respectively.
I expected the `rational-modules` to load, however, these are not loaded when I launch emacs. I can use `load-file` to load `config.el` and all modules are loaded.
What am I missing?
I am on `"GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0)
 of 2022-05-06"`

**Comment by vaidyafamily** [comment]
According to the [cusomization section](https://github.com/SystemCrafters/rational-emacs#customization), it looks like you want your config.el in one of the two following locations:

**Comment by md-arif-shaikh** [comment]
Ahh, okay, so I need to place those two files under one of these directories. I am so used to only one directory for emacs config that I assumed it would be the .emacs.d. My bad. Thanks!!

**Comment by oatmealm** [comment]
I'm seeing the same problem now though .config/crafted-emacs was created and I moved the example config files there. Nothing seem to happen and crafted loads as there's no config at all... not sure what's happening because it did work for me before.
