### ISSUE TITLE
Add a usage disclaimer in README.org

### ISSUE THREAD

**Issue by daviwil** [SystemCrafters/rational-emacs#25]
This project is receiving a lot of excellent PRs!  Since we're still in the early phases of figuring out the right way to structure everything, it'd probably be worthwhile to add a disclaimer to let potential users know that this config could break for them on their next pull due to things changing quickly.

We shouldn't discourage people from trying the configuration, though!

**Comment by jeastman** [comment]
I figure it is easier to sort out wording here than in a series of pull requests, so... how is this?

    Please note: rational-emacs is under active development. While the intent
    of this project is to provide a stable Emacs configuration for use by
    anyone, it is not yet stable enough for everyday or production use.  The
    rapid pace of changes could cause your configuration to break on your next
    pull of the repository. If you are not expecting or prepared to encounter
    such issues, we would recommend you wait for things to stabilize a bit
    before using.

**Comment by ajxn** [comment]
Maybe a suggestion or two how one could recover from problems like that?
Like 
- Which switch to use to get Emacs to debug `init.el` file? (`emacs --debug-init`)
- Which switch to start without reading `init.el` configuration? (`emacs --no-init-file`)
- That `Cemacs2` could be a solution for that? (???)
- How to back with `git` (???)
- How to generate 'HTML`, `PDF` or `ODT` documents from the `README.org` file for reference? (`C-c C-e h h` and `C-c C-e l p` or  `C-c C-e o o`).

**Comment by daviwil** [comment]
Fixed by #55.
