### ISSUE TITLE
mirror this on other common/popular git-forge´s for easy contribution

### ISSUE THREAD

**Issue by erikLundstedt** [SystemCrafters/rational-emacs#27]
its all in the title

I was mainly thinking about gitlab(what I use) and source-hut(which you might already be doing)

**Comment by daviwil** [comment]
I think having it mirrored on multiple places would make it hard for me to keep up with the contributions and I have pretty limited time as it is.  Let's keep it to GitHub only for now and I'll reconsider if I hear a lot more requests for a particular primary platform.
