### ISSUE TITLE
make it read ~/.config/rational-emacs/custom-modules for... 

### ISSUE THREAD

**Issue by erikLundstedt** [SystemCrafters/rational-emacs#29]
`dramatic pause`
...custom modules, perfect for modularizing your own config without having to follow the [principles](https://github.com/SystemCrafters/rational-emacs/blob/master/README.org#principles) (this might fit better in something like personal-modules or equivalent) and for keeping a personal or public list of modules that cant/havent yet been merged into the regular modules directory

@daviwil

**Comment by erikLundstedt** [comment]
it would also make it easier to host modules on a git-forge not owned by MicroSoft...

**Comment by JulienTant** [comment]
I do have that in my personal `config.el` 

```elisp
;; load my own modules
(when (file-directory-p (expand-file-name "modules/" rational-config-path))
                        (add-to-list 'load-path (expand-file-name "modules/" rational-config-path)))
```

if it is desired, I can make a PR to have this in `init.el`

**Comment by erikLundstedt** [comment]
> I do have that in my personal `config.el`
> 
 ```emacs-lisp
 ;; load my own modules
 (when (file-directory-p (expand-file-name "modules/" rational-config-path))
>                         (add-to-list 'load-path (expand-file-name "modules/" rational-config-path)))
```
> 
> if it is desired, I can make a PR to have this in `init.el`

that would be great

its a quality of life thing but still really useful

**Comment by erikLundstedt** [comment]
> I do have that in my personal `config.el`
> 
```emacs-lisp
 ;; load my own modules
 (when (file-directory-p (expand-file-name "modules/" rational-config-path))
                         (add-to-list 'load-path (expand-file-name "modules/" rational-config-path)))
```
> 
> if it is desired, I can make a PR to have this in `init.el`



---
# something like this is what i would recomend
this will also load subdirectories which might be a good idea in the `init.el`
this allows for having :file_folder: ` custom-modules`  filled with git repositories(this is what i am doing, allows for readme.org etc )

```emacs-lisp

(when (file-directory-p (expand-file-name "custom-modules/" rational-config-path))
  (add-to-list 'load-path (expand-file-name "custom-modules/" rational-config-path))

  ;;(add-to-list 'load-path (expand-file-name "custom-modules/" rational-config-path))


  (let ((default-directory (expand-file-name "custom-modules/" rational-config-path)))
    (normal-top-level-add-subdirs-to-load-path))
)
```
