### ISSUE TITLE
No command history in evil-mode from previous session

### ISSUE THREAD

**Issue by rotlaus** [SystemCrafters/rational-emacs#31]
When typing : to start a command after starting emacs i get no command history to scroll through from the previous session.
Message Buffer says 
`previous-matching-history-element: No earlier matching history item`

I do get a history of commands from the current session, but after a fresh emacs start it's empty.

**Comment by rotlaus** [comment]
Enabling savehist-mode fixes my problem. 
I could make a pull request. Should it be enabled always ( in rational-defaults) or only for evil mode (in rational-evil)?

**Comment by jeffbowman** [comment]
I don't preserve kill-ring, search, et.al. like that. I actually didn't know that was a thing! So, I learned something. Neat!
