### ISSUE TITLE
theme and font settings don't work starting emacs as a daemon

### ISSUE THREAD

**Issue by fnt400** [SystemCrafters/rational-emacs#37]
I tried to set my theme (prot's one) and font (iosevka) as raccomended in the README file. 
It works fine starting emacs normally, but if I start emacs as daemon (or with systemd) and than I create a new frame with emacsclient -c  it has the blueish default theme and another font.

**Comment by jeffbowman** [comment]
Try setting those in the `rational-emacs/early-config.el` file. See if that helps.

In general, setting fonts and frame based configuration in early-init (or early-config.el in the case of rational-emacs), is a better idea because they get set before the frame exists so the springy resizing thing does not happen when the frame becomes visible. In daemon mode, that *should* help with getting the emacs client frame looking the way you want.

**Comment by fnt400** [comment]
> @fnt400 Try setting those in the `rational-emacs/early-config.el` file. See if that helps.
thankyou for the advice. I tried but it didn't work. The font do not change when starting as a daemon. 
The theme setting, instead, gives an error because it can't find the theme itself (probably it can be fixed adding a load-path but I didn't try)

**Comment by jeffbowman** [comment]
@fnt400 The reason you are seeing the blue color has to do with the default configuration in the rational-emacs early-init.el file, specifically these 2 lines:

https://github.com/SystemCrafters/rational-emacs/blob/master/early-init.el#L29-L30

which set the default foreground and background colors.

In your `rational-config-path/early-config.el` you need to add this configuration to get rid of it:

```
(setf default-frame-alist (assq-delete-all 'background-color default-frame-alist))
(setf default-frame-alist (assq-delete-all 'foreground-color default-frame-alist))
```

Then your code to load a them like this `(load-theme 'modus-vivendi t)` (probably in your `rational-config-path/config.el` file)  should work.

**Comment by fnt400** [comment]
Great! Now the theme starts correctly! Unfortunately the font setting doesn't. I still have to set it manually when I create the first frame (but that's not a big problem).

**Comment by jeffbowman** [comment]
This is what my `early-config.el` file has. the font gets set correctly as does the theme. Does this help you?

https://gist.github.com/jeffbowman/7d0e20df9321aaa28468c2a32503d322

**Comment by fnt400** [comment]
Yes!!! That did the trick! I was using the function set-face-attribute, instead of custom-set-faces.
Thank you very much!!
