### ISSUE TITLE
${HOME}/.rational-emacs is ignored during startup

### ISSUE THREAD

**Issue by ingorichter** [SystemCrafters/rational-emacs#56]
After this commit https://github.com/SystemCrafters/rational-emacs/commit/4365414e4a8857f417c02d80c1f01150198eff6c my `${HOME}/.rational-emacs` is no longer considered for `rational-config-path`.

On my machine it always resolves to `${HOME}/.config/rational-emacs`

**Comment by daviwil** [comment]
Thanks for the report!  @jeffbowman do you mind taking a look?

**Comment by jeffbowman** [comment]
Yep, I'll look into this.
