### ISSUE TITLE
Define customization group

### ISSUE THREAD

**Issue by jeastman** [SystemCrafters/rational-emacs#62]
There needs to be a `defgroup` for the `rational` customize group somewhere to link the custom variables into.

I was thinking something along the lines of the following:

    (defgroup 'rational
        "A sensible starting point for hacking your own Emacs configuration."
        :group 'emacs)

The problem is that we need some place to define this which is guaranteed to be loaded. A discussion of this common source is also discussed in #59.

**Comment by jeastman** [comment]
See relevant comments in from #52 by @jeffbowman. 

> So have a defgroup for rational that is a "top level" customization and overrides things in the init.el file
>  ...
> in init.el
>
>    (defgroup rational nil "Rational Emacs Configuration")

**Comment by abarocio80** [comment]
I think that it could be on `early-init.el`, since it will be the base to all customizations in this project.

Defining it here won't hurt (afaik) the startup time, and will prevent any conflicts with any package that want to use customizations.

**Comment by ajxn** [comment]
Should this not be done in `early-init.el`, so the variables are available from the start?  Or what is concensus of using `early-init.el`?  That will also involve loading of the customization variables.

**Comment by jeastman** [comment]
My understanding of the intent of `early-init.el` file is to provide a place to specifically initialize things which occur before the `init.el` is loaded. The manual calls out package and GUI initialization as examples.

From the Emacs manual ("The Init File"):
> The difference between the early init file and the regular init file is that the early init file is loaded much earlier during the startup process, so you can use it to customize some things that are initialized before loading the regular init file.

From the Emacs manual ("The Early Init File"):
> This file is loaded before the package system and GUI is initialized, so in it you can customize variables that affect frame appearance as well as the package initialization process...

I believe we should limit what is done in the `early-init.el` to only what is absolutely necessary to do there. I further believe this should be limited to package system configuration (an area which still needs to be addressed - see #72), and anything related to frame initialization (so the GUI does not "flash" during initialization).

Now the question is do we want to allow customization of `rational-emacs` during `early-init.el`? Since this file is loaded _before_ the user's `config.el` (the Rational Emacs user's config), there is not really an opportunity for the user to influence/customize the Rational Emacs bits before the `early-init.el` loads. We could create another user early init (`early-config.el`?) which is tied into the Rational Emacs `early-init.el`, but I am pretty sure I do not like that idea very much. It just seems to confuse things further. Thus, if there is no possibility of customizing Rational Emacs as part of the `early-init.el`, then there would be no reason to define the custom group at that point either.

Customization of Rational Emacs is something we need to tackle conceptually. Since we are not dictating the user's `config.el` (meaning we cannot assume the modules which are loaded or the order in which they are loaded), we will likely need to handle most configuration via callbacks associated with custom variables (via `:set`) , and not just blindly execute code in the different `rational-*` modules.  This likely requires its own discussion thread.

My recommendation would be to _not_ expose the `early-init.el` for user configuration and limit what we do in that file. "Custom" initialization (the set up of all Rational Emacs custom variables and the like) would take place as part of `init.el`. I'm completely open to other ideas, that is just where my thinking lies at this time.

**Comment by jeffbowman** [comment]
See line 79 in early-init.el, we already provide a hook for the user to provide their own early config.el. 

What I think we have in early-init.el is reasonable and easy to override if the user chooses.

**Comment by ajxn** [comment]
Sorry, @jeffbowman. Either we are talking about different things, or you don't understand.

`custom-file` are not for users to change, it is changed through customication UI i Emacs.

**Comment by jeffbowman** [comment]
Perhaps I missed the point, I thought we were talking about the early-init file in the context of customize
