### ISSUE TITLE
Keycast in doom modeline - keycast-mode: Cannot turn on keycast-mode.  mode-line-misc-info not found in mode-line-format.  Try customizing keycast-mode-line-insert-after. 

### ISSUE THREAD

**Issue by terxw** [SystemCrafters/rational-emacs#71]
# Problem

After trying out rational emacs and porting my config (which is from emacs from scratch series, very good for learning emacs elisp etc. ) I noticed that I was missing keycast pressed keys and actions in my new (doom) modeline.

# Solution

 After investigating I found out that I am using older version in my old config and my already present workaround for doom modeline is not working, but there is updated solution in the same issue where I found my previous answer.

Reference:

https://github.com/tarsius/keycast/issues/7#issuecomment-1017178197
```
(with-eval-after-load 'keycast
  (define-minor-mode keycast-mode
    "Show current command and its key binding in the mode line."
    :global t
    (if keycast-mode
        (add-hook 'pre-command-hook 'keycast--update t)
      (remove-hook 'pre-command-hook 'keycast--update)))

  (add-to-list 'global-mode-string '("" keycast-mode-line)))
(keycast-mode)

```

I would suggest to add the solution from kecast github to  rational-screencast.el,  probably dependent on  the value of ```rational-ui-use-doom-modeline``` from [PR 45](https://github.com/SystemCrafters/rational-emacs/pull/45)

**Comment by jeffbowman** [comment]
Closing this as there seems to be no further movement and per the discussion on #45 (also closed) which discussed modeline changes and whether we would do them. The suggestion there was to add a `rational-mode-line` module, which has not materialized, so maybe the community isn't interested in that feature? This can be reopened if needed to continue the discussion or to link with a PR.
