### ISSUE TITLE
(rational-ui) All-the-icons in doom-modeline not rendering on Windows

### ISSUE THREAD

**Issue by hey-jeldo** [SystemCrafters/rational-emacs#80]
I installed Emacs on the Windows computer at my workplace (just to play with it in case of downtime) and after loading rational-emacs noticed that the icons in doom-modeline were not rendering. Probably encoding...

Maybe setting all the variables might help, can't test this right now.
``` emacs-lisp
;; UTF-8
(setq locale-coding-system 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(prefer-coding-system 'utf-8)
```

**Comment by bkaestner** [comment]
`all-the-icons` needs `M-x all-the-icons-install-fonts`. Unfortunately, on Windows `all-the-icons-install-fonts` will only download the icons. You still need to install them from hand afterwards.

See also the [remark in ati's README](https://github.com/domtronn/all-the-icons.el#installing-fonts):

> For Windows, this function will prompt for a download directory for you to install them manually.

**Comment by hey-jeldo** [comment]
Thanks, i didn't know!

**Comment by ajxn** [comment]
This should really be documented in `README.org` and that is not the only thing.  Spelling software should probably also be loaded, or suggested.  So about software to be able to export `.org` to PDF and  LibreOffice `.otd` formats.  This bit me too.

**Comment by ajxn** [comment]
Thar some fonts/icons/programs need to be installed for it to work.  That need to go into README.org
