### ISSUE TITLE
Avoid changing emacs default  keybindings while making modules

### ISSUE THREAD

**Issue by HumHongeKamyaab** [SystemCrafters/rational-emacs#88]
We should not change the default keybindings of emacs while making rational modules.
e.g., C-u which default for using arguments in emacs commands is changed in this line
https://github.com/SystemCrafters/rational-emacs/blob/cd2a9bc31310fd502e51a52da0d499a1da86f712/modules/rational-evil.el#L30
I am also evil user but never changed this keybinding for evil usage.
Users can make these changes in keybindings in their rational emacs config file. It should be philosophy while making other modules also.

**Comment by jeffbowman** [comment]
We may need to expand the `Contributing` section of the README.org file to include some of these things. This one, the preference for `customize-set-variable` over `setq`, using `defcustom` rather than `defvar` for customizable parts of a module, etc.

**Comment by daviwil** [comment]
Yep, I shouldn't have included that setting by default since it breaks default Emacs usage.  Feel free to send a PR to take it out!

**Comment by jeffbowman** [comment]
Fixed in #119
