### ISSUE TITLE
straight.el vs package.el - Which should we stick with?

### ISSUE THREAD

**Issue by daviwil** [SystemCrafters/rational-emacs#94]
Discuss!

**Comment by bkaestner** [comment]
Hm. That does depend on *what* Rational Emacs is supposed to be, isn't it? We might need to discuss that one too. If RE is supposed to be closer to the original Emacs and mostly provide reasonable defaults, then I'd strongly suggest `package.el`. But if it's an opinionated piece, then `straight.el` might be fine.

**Comment by bkaestner** [comment]
Going by the current README and the principles stated there, I'd definitely go with the built-in `package.el`:

> # Principles
> This configuration and all associated modules intend to follow the below priniciples. [...]
> ## Minimal, modular configuration [...]
> ## Prioritize built-in Emacs functionality [...]

But I'm not a `straight.el` user and thus don't quite know its possible advantages.

**Comment by jeastman** [comment]
I liked @daviwil's thoughts on being able to pin to other git repos to support a time when modules may themselves become their own projects. However, we are no where close to that. 

I feel it would be best to go with `package.el` for now. If we run into an issue which that cannot solve, we can address it at that time.

**Comment by jeffbowman** [comment]
Any additional thoughts? We seem to be trending toward using `package.el` instead of `straight` as the default package manager here. 

cc: @daviwil

**Comment by jeffbowman** [comment]
### NOTICE!!!!

There seems to be no further discussion here, and the consensus seems to be to prefer `package.el` as it is built-in. I'll begin the work to make that change on Monday, 5 April 2022 unless there is further discussion here.

**Comment by jeastman** [comment]
After looking at #120, I'm a bit confused on the plan.

Is the idea to allow the user to use `straight` if they decide to configure it? I think that might get us into some mixed up scenarios. If we allow the user to choose, we will need to make sure only one of them is ever active.

**Comment by jeffbowman** [comment]
So, I was of two minds on that. I left it in the macro because we _had_ used it and maybe someone who preferred `straight` wouldn't have to do anything other than add the bootstrap to their `early-config.el` file. I'd rather take it out now that I've been tinkering with it, especially since the bootstrap stuff is gone for `straight`.

**Comment by jeffbowman** [comment]
@jeastman I've updated the PR, if you could review one more time please.

**Comment by theophilusx** [comment]
Unfortunately I missed this thread. It is disappointing straight support has gone as I find it much more reliable than package.el. As an example, I just did a completely fresh install of rational-emacs on a VM and it now fails to start correctly with errors relating to problems in the package.el version of evil-ex.  Having been a package.el user for a long time, I know how to resolve these problems, but their resolution is more work/effort than with straight.el. My original hope was that this project would provide a modular repository which would allow users to easily select the 'modules' they want, including preferred package management. 

I understand this is the direction the community has decided upon and that is fine. I'm very thankful for the good ideas and exmaples this has provided, but I think for now, I'll go my own way. I'm particularly thankful for this project introducing me to embark, vertico et. al.  Keep up the good work!

**Comment by jeffbowman** [comment]
@theophilusx  You can probably still use straight if you with rational, I tried to keep it at least "friendly" to the concept. In your `early-config.el` you'll need to turn off `package-enable-at-startup` and provide the bootstrap code for `straight`. You can then either advise or redefine the `rational-package-install-package` macro to use `straight-use-package`.  

That being said, thanks for your kind words! The best thing about Emacs is you can choose your own way to make things work best for you! Thanks for participating with us here, we hope to see you back from time to time... until then - all the best!

**Comment by jeffbowman** [comment]
For those who are interested, please see the recent additional of an example configuration to use `straight.el` instead of `package.el`. It is in the `examples/straight/` folder. 

cc: @theophilusx
